site_name: Wifi CTF (ReadteamRD)

theme: readthedocs

nav:
 - Home: 'index.md'
 - Recon: 'recon.md'
 - Gain Access: 'gain_access.md'
 - Escalate: 'escalate.md'
 - Cracking: 'cracking.md'
 - find_flags: 'find_flags.md'


markdown_extensions:
 - attr_list
 - admonition
plugins:
 - search
